Rails.application.routes.draw do

  # RESTful routes generated by g resource
  resources :claims
  resources :users
  # get '/users', to: 'users#index'
  # Routing logic: fallback requests for React Router.
  # Leave this here to help deploy your app later!
  get "*path", to: "fallback#index", constraints: ->(req) { !req.xhr? && req.format.html? }
end
